### ISSUE TITLE
Node-red + real time feedback from sensors

### ISSUE THREAD

**Issue by kobibeja** [lucacalcaterra/risco-mqtt-bridge#21]
Hello,
Someone is tried to use this with node-red platform and get feedback form the **_riscopanel/dects_** topic in real time when sensor is interrupted while alarm is **disarmed**?
I'm trying to use the sensors for running lighting scenario.

BR
Kobi

**Comment by pergolafabio** [comment]
Don't think it will work for lighting, I think there is a delay , not sure if dect are also in the polling queue

**Comment by pergolafabio** [comment]
did you already play with it? is there a delay on the state of dect when system is disarmed?

**Comment by kobibeja** [comment]
Yes I did play with it and it's working fine, arm/disarm (get and set) regarding dect I didn't get in real time feedback

**Comment by lucacalcaterra** [comment]
@kobibeja Cannot have a realtime feedback. Polling from cloud it's done with a delay interval . You cannot minimize latency lowering the value of polling, but never tried too much low values (risco can be ban your account due to server overload)

The realtime feedback it's possible only if risco implement a public API that support it, or directly from alarm panel ... but ... since the protocol it's encrypted , we cannot do it.

**Comment by pergolafabio** [comment]
is the protocol on panel always encrypted? maybe on older panels its not encrypted, i still have older firmware loaded on my lightsts

**Comment by lucacalcaterra** [comment]
read this:

https://cybergibbons.com/alarms-2/vulnerability-in-risco-lightsys-protocol-encryption/

**Comment by pergolafabio** [comment]
hmm, interesting, but messages are encrypted it seems
messages like arm/disarm?
i see you replyd there also on that blog :)  but you didnt manage?

**Comment by lucacalcaterra** [comment]
All communications are encrypted. Left this route :-(
